const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();}
const API='https://clipsmalsum.duckdns.org/academy-api';
const state={route:'home',selectedCourse:'course-1',selectedLesson:'lesson-1',theme:localStorage.getItem('academy-theme')||'light',language:localStorage.getItem('academy-language')||'ce',fontScale:Number(localStorage.getItem('academy-font-scale')||'1'),favorites:JSON.parse(localStorage.getItem('academy-favorites')||'[]'),completed:JSON.parse(localStorage.getItem('academy-completed')||'[]'),search:''};
const I={
ru:{home:'Главная',courses:'Курсы',favorites:'Избранное',profile:'Профиль',quick:'Быстрый доступ',allSections:'Все учебные разделы',search:'Поиск',findLesson:'Найти нужный урок',savedLessons:'Сохранённые уроки',progress:'Прогресс',track:'Отслеживание прохождения',myProgress:'Мой прогресс',more:'Подробнее',lessonsDone:'Пройдено уроков',finished:'завершено',studySpace:'Учебное пространство',continueStudy:'Продолжить обучение',searchCourses:'Поиск по курсам и урокам',course:'Курс',allCourses:'Все курсы',studySection:'Учебный раздел',lessons:'Уроки',lesson:'Урок',audio:'Аудио',lessonAudio:'Аудио урока',initialText:'Начальный текст',materials:'Материалы',lessonPdf:'PDF к уроку',fileLater:'Файл будет добавлен позже',open:'Открыть',noPdf:'Для этого тестового урока PDF не предусмотрен.',inFavorites:'В избранном',toFavorites:'В избранное',lessonDone:'Урок пройден',markDone:'Отметить пройденным',previous:'Предыдущий',next:'Следующий',enterLesson:'Введите название урока',nothingFound:'Ничего не найдено',tryAnother:'Попробуйте другой запрос',empty:'Пока пусто',emptyFavorites:'Добавляйте уроки в избранное, чтобы быстро возвращаться к ним.',totalProgress:'Общий прогресс',passed:'Пройдено',testLessons:'тестовых уроков',passedLessons:'Пройденные уроки',noPassed:'Нет пройденных уроков',markHint:'Отметьте урок как пройденный, и он появится здесь.',academyStudent:'Ученик Академии',darkTheme:'Тёмная тема',lightTheme:'Светлая тема',enableLight:'Включить светлую тему',enableDark:'Включить тёмную тему',changeDesign:'Изменить оформление приложения',interfaceLanguage:'Язык интерфейса',now:'Сейчас',russian:'Русский',chechen:'Чеченский',about:'О версии',withoutMaterials:'Без настоящих материалов курса',addedFavorite:'Добавлено в избранное',removedFavorite:'Удалено из избранного',markedDone:'Урок отмечен как пройденный',markRemoved:'Отметка снята',playerLater:'Тестовый плеер: реальное аудио добавим позже',pdfLater:'PDF будет подключён позже'},
ce:{home:'Коьрта агIо',courses:'Курсаш',favorites:'Хаьржинарш',profile:'Профиль',quick:'Сиха аьтто',allSections:'Дешаран дерриге дакъош',search:'Лехар',findLesson:'Оьшуш йолу урок каро',savedLessons:'Iалашдина урокаш',progress:'Кхиам',track:'Чекхдаларна тIехьажар',myProgress:'Сан кхиам',more:'Кхин а дуьззина',lessonsDone:'Чекхдаьхна урокаш',finished:'чекхдаьккхина',studySpace:'Дешаран майда',continueStudy:'Дешар дIадахьа',searchCourses:'Курсашкахула а, урокашкахула а лехар',course:'Курс',allCourses:'Дерриге курсаш',studySection:'Дешаран дакъа',lessons:'Урокаш',lesson:'Урок',audio:'Аудио',lessonAudio:'Урокан аудио',initialText:'Юьхьанцара текст',materials:'ГIирсаш',lessonPdf:'Урокан PDF',fileLater:'Файл тIаьхьо тIетухур ю',open:'Схьаделлан',noPdf:'ХӀокху тестови урокан PDF ца карайо',inFavorites:'Хаьржинчехь',toFavorites:'Хаьржинчу',lessonDone:'Урок чекхдаьккхина',markDone:'Чекхдаьккхина аьлла билгалдан',previous:'Хьалхара',next:'ТIаьхьара',enterLesson:'Урокан цIе дIаязъе',nothingFound:'ХIума ца карийна',tryAnother:'Кхин дош леха хьажа',empty:'ХIинцака ясса ю',emptyFavorites:'Сиха юхаверзархьама, урокаш хьалхатеттинчу тIетиха',totalProgress:'Юкъара кхиам',passed:'Чекхдаьккхина',testLessons:'тестови урокаш',passedLessons:'Чекхдаьхна урокаш',noPassed:'Чекхдаьхна урокаш яц',markHint:'Урок чекхдаьккхина аьлла билгалбе, иза кхузахь гучуберг ю',academyStudent:'Академин дешархо',darkTheme:'Бодане тема',lightTheme:'Серламе тема',enableLight:'Серламе тема лато',enableDark:'Бодане тема лато',changeDesign:'Приложенин куц хийца',interfaceLanguage:'Интерфейсан мотт',now:'ХIинца',russian:'Оьрсийн',chechen:'Нохчийн',about:'Версех лаьцна',withoutMaterials:'Курсан баккъалла болу гIирсаш боцуш',addedFavorite:'Хьалхатеттинчу тIетоьхна',removedFavorite:'Хьалхатеттинчуьра дIаяьккхина',markedDone:'Урок чекхдаьккхина аьлла билгалйина',markRemoved:'Билгало дIаяьккхина',playerLater:'Тестови плеер: баккъалла долу аудио тIаьхьо тIетухур ду',pdfLater:'PDF тIаьхьо тIехоттур ю'}};
const t=k=>I[state.language][k]||k;
const lessonTitles=['1-ра дарс','2-гӀа дарс','3-гӀа дарс','4-гӀа дарс','5-гӀа дарс','6-гӀа дарс','7-гӀа дарс','8-гӀа дарс','9-гӀа дарс','10-гӀа дарс','11-гӀа дарс','12-гӀа дарс','13-гӀа дарс','14-гӀа дарс','15-гӀа дарс','16-гIа дарс','17-гIа дарс','18-гIа дарс','19-гIа дарс','20-гIа дарс'];
const lessons=lessonTitles.map((lessonTitle,i)=>({id:`lesson-${i+1}`,courseId:'course-1',number:i+1,title:lessonTitle,audio:`${API}/lesson/${i+1}/audio`}));
const courses=[{id:'course-1',title:'Курс 1',lessons:lessons.map(x=>x.id),pdf:`${API}/course/1/pdf`}];
const view=document.getElementById('view'),title=document.getElementById('page-title'),themeToggle=document.getElementById('theme-toggle');document.documentElement.dataset.theme=state.theme;
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function applyFontScale(){state.fontScale=Math.min(2,Math.max(.7,state.fontScale||1));document.documentElement.style.setProperty('--font-scale',String(state.fontScale));}
function save(){localStorage.setItem('academy-theme',state.theme);localStorage.setItem('academy-language',state.language);localStorage.setItem('academy-font-scale',String(state.fontScale));localStorage.setItem('academy-favorites',JSON.stringify(state.favorites));localStorage.setItem('academy-completed',JSON.stringify(state.completed));}
function updateThemeButton(){if(!themeToggle)return;const dark=state.theme==='dark';themeToggle.innerHTML=`<span class="theme-symbol">${dark?'☀️':'🌙'}</span>`;themeToggle.setAttribute('aria-label',dark?t('enableLight'):t('enableDark'));themeToggle.title=dark?t('lightTheme'):t('darkTheme');}
function updateNav(){const labels={home:t('home'),courses:t('courses'),favorites:t('favorites'),profile:t('profile')};document.querySelectorAll('.nav-item').forEach(b=>{const s=b.querySelector('small');if(s)s.textContent=labels[b.dataset.route]||''});document.documentElement.lang=state.language==='ce'?'ce':'ru'}
function toast(m){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=m;requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>e.classList.remove('show'),1600)}
function haptic(){try{tg?.HapticFeedback?.impactOccurred('light')}catch(_){}}
function navigate(route,o={}){state.route=route;Object.assign(state,o);render();window.scrollTo({top:0,behavior:'smooth'});haptic()}
function setActiveNav(route){const base=['course','lesson','search','progress'].includes(route)?'courses':route;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===base||(route==='home'&&b.dataset.route==='home')))}
function progressValue(){return lessons.length?Math.round(state.completed.filter(id=>lessons.some(l=>l.id===id)).length/lessons.length*100):0}
function renderHome(){title.textContent=t('home');const p=progressValue(),done=state.completed.filter(id=>lessons.some(l=>l.id===id)).length;view.innerHTML=`<section class="hero"><div class="hero-kicker">${t('studySpace')}</div><h2>Ӏакъидатан Академия</h2><p>${t('course')} 1 · 20 ${t('lessons')}</p><button class="primary-btn" data-action="continue">${t('continueStudy')}</button></section><div class="section-head"><h2>${t('quick')}</h2></div><section class="grid-2"><button class="card quick-card" data-route-btn="courses"><span class="quick-icon">▤</span><span><div class="quick-title">${t('courses')}</div><div class="quick-sub">${t('allSections')}</div></span></button><button class="card quick-card" data-route-btn="search"><span class="quick-icon">⌕</span><span><div class="quick-title">${t('search')}</div><div class="quick-sub">${t('findLesson')}</div></span></button><button class="card quick-card" data-route-btn="favorites"><span class="quick-icon">♡</span><span><div class="quick-title">${t('favorites')}</div><div class="quick-sub">${t('savedLessons')}</div></span></button><button class="card quick-card" data-route-btn="progress"><span class="quick-icon">◎</span><span><div class="quick-title">${t('progress')}</div><div class="quick-sub">${t('track')}</div></span></button></section><div class="section-head"><h2>${t('myProgress')}</h2><button class="link-btn" data-route-btn="progress">${t('more')}</button></div><section class="card progress-card"><div class="progress-row"><span>${t('lessonsDone')}</span><strong>${done}/${lessons.length}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><div class="quick-sub">${p}% ${t('finished')}</div></section>`}
function renderCourses(){title.textContent=t('courses');view.innerHTML=`<div class="search-wrap"><input id="course-search" placeholder="${t('searchCourses')}" value="${escapeHtml(state.search)}"><span>⌕</span></div><section class="course-list">${courses.map((c,i)=>`<button class="course-card" data-course="${c.id}"><div class="course-top"><span class="badge">${t('course')} ${i+1}</span><span>›</span></div><h3>${c.title}</h3><div class="quick-sub" style="margin-top:12px">${c.lessons.length} ${t('lessons')}</div></button>`).join('')}</section>`}
function renderCourse(){const c=courses.find(x=>x.id===state.selectedCourse)||courses[0],ls=lessons.filter(l=>l.courseId===c.id);title.textContent=c.title;view.innerHTML=`<button class="link-btn" data-back="courses">← ${t('allCourses')}</button><section class="card"><span class="badge">${t('studySection')}</span><h2 style="margin:10px 0 6px">${c.title}</h2><p style="margin:0;color:var(--muted)">${ls.length} ${t('lessons')}</p></section><div class="section-head"><h2>${t('materials')}</h2></div><section class="card"><div class="progress-row"><strong>PDF</strong><a class="secondary-btn" href="${c.pdf}" target="_blank" rel="noopener">${t('open')}</a></div></section><div class="section-head"><h2>${t('lessons')}</h2><span class="quick-sub">${ls.length}</span></div><section class="lesson-list">${ls.map(lessonCard).join('')}</section>`}
function lessonCard(l){const f=state.favorites.includes(l.id),d=state.completed.includes(l.id);return `<div class="lesson-card ${d?'completed':''}"><div class="lesson-top"><button class="link-btn" style="text-align:left;padding:0;flex:1;color:var(--text)" data-lesson="${l.id}"><span class="badge">${t('lesson')} ${l.number}</span><h3>${l.title}</h3><p>${t('audio')}</p></button><button class="favorite-btn" data-favorite="${l.id}" aria-label="${t('favorites')}">${f?'♥':'♡'}</button></div></div>`}
function renderLesson(){const l=lessons.find(x=>x.id===state.selectedLesson)||lessons[0],c=courses.find(x=>x.id===l.courseId),ls=lessons.filter(x=>x.courseId===l.courseId),i=ls.findIndex(x=>x.id===l.id),f=state.favorites.includes(l.id),d=state.completed.includes(l.id);title.textContent=`${t('lesson')} ${l.number}`;view.innerHTML=`<button class="link-btn" data-back="course">← ${c.title}</button><section class="lesson-screen"><div class="lesson-header"><div class="hero-kicker">${t('lesson')} ${l.number}</div><h2>${l.title}</h2><p>${c.title}</p></div><section class="card"><div class="section-head" style="margin-top:0"><h2>${t('lessonAudio')}</h2></div><audio controls preload="metadata" playsinline src="${l.audio}" style="width:100%"></audio></section><div class="row-actions"><button class="secondary-btn" data-favorite="${l.id}">${f?t('inFavorites'):t('toFavorites')}</button><button class="primary-btn" data-complete="${l.id}">${d?t('lessonDone'):t('markDone')}</button></div><div class="row-actions"><button class="secondary-btn" data-prev ${i===0?'disabled':''}>← ${t('previous')}</button><button class="secondary-btn" data-next ${i===ls.length-1?'disabled':''}>${t('next')} →</button></div></section>`}
function renderSearch(){title.textContent=t('search');const q=state.search.trim().toLowerCase(),found=lessons.filter(l=>!q||l.title.toLowerCase().includes(q));view.innerHTML=`<div class="search-wrap"><input id="lesson-search" autofocus placeholder="${t('enterLesson')}" value="${escapeHtml(state.search)}"><span>⌕</span></div><section class="lesson-list">${found.length?found.map(lessonCard).join(''):`<div class="empty-state"><div class="empty-icon">⌕</div><h3>${t('nothingFound')}</h3><p>${t('tryAnother')}</p></div>`}</section>`}
function renderFavorites(){title.textContent=t('favorites');const ls=lessons.filter(l=>state.favorites.includes(l.id));view.innerHTML=ls.length?`<section class="lesson-list">${ls.map(lessonCard).join('')}</section>`:`<div class="empty-state"><div class="empty-icon">♡</div><h3>${t('empty')}</h3><p>${t('emptyFavorites')}</p></div>`}
function renderProgress(){title.textContent=t('progress');const done=lessons.filter(l=>state.completed.includes(l.id)),p=progressValue();view.innerHTML=`<section class="card progress-card"><div class="progress-row"><span>${t('totalProgress')}</span><strong>${p}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><div class="quick-sub">${t('passed')}: ${done.length}/${lessons.length}</div></section><div class="section-head"><h2>${t('passedLessons')}</h2></div>${done.length?`<section class="lesson-list">${done.map(lessonCard).join('')}</section>`:`<div class="empty-state"><h3>${t('noPassed')}</h3><p>${t('markHint')}</p></div>`}`}
function renderProfile(){title.textContent=t('profile');const dark=state.theme==='dark';view.innerHTML=`<section class="card"><div class="profile-row"><div class="avatar">ӀА</div><div><h3 style="margin:0">Ӏакъидатан Академия</h3><p style="margin:5px 0 0;color:var(--muted)">${t('academyStudent')}</p></div></div></section><div class="section-head"><h2>${t('changeDesign')}</h2></div><section class="card settings-list"><div class="setting-row"><div><strong>${dark?t('darkTheme'):t('lightTheme')}</strong><div class="quick-sub">${dark?t('enableLight'):t('enableDark')}</div></div><button class="secondary-btn" data-setting="theme">${dark?'☀️':'🌙'}</button></div><div class="setting-row font-setting" style="align-items:center"><div><strong>Aa</strong></div><div class="row-actions font-controls" style="margin:0;gap:8px;flex:0 0 auto"><button class="secondary-btn" data-font="minus" aria-label="A−">A−</button><button class="secondary-btn font-value" data-font="reset" aria-label="${Math.round(state.fontScale*100)}%">${Math.round(state.fontScale*100)}%</button><button class="secondary-btn" data-font="plus" aria-label="A+">A+</button></div></div><div class="setting-row"><div><strong>${t('interfaceLanguage')}</strong><div class="quick-sub">${t('now')}: ${state.language==='ce'?t('chechen'):t('russian')}</div></div><div class="row-actions" style="margin:0"><button class="secondary-btn" data-lang="ru">${t('russian')}</button><button class="secondary-btn" data-lang="ce">${t('chechen')}</button></div></div></section>`}
function setFontSize(action){if(action==='minus')state.fontScale-=.1;else if(action==='plus')state.fontScale+=.1;else state.fontScale=1;state.fontScale=Math.round(Math.min(2,Math.max(.7,state.fontScale))*10)/10;applyFontScale();save();render();haptic()}
function render(){applyFontScale();updateThemeButton();updateNav();setActiveNav(state.route);const map={home:renderHome,courses:renderCourses,course:renderCourse,lesson:renderLesson,search:renderSearch,favorites:renderFavorites,progress:renderProgress,profile:renderProfile};(map[state.route]||renderHome)()}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();toast(state.favorites.includes(id)?t('addedFavorite'):t('removedFavorite'));render();haptic()}
function toggleComplete(id){state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();toast(state.completed.includes(id)?t('markedDone'):t('markRemoved'));render();haptic()}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav)return navigate(nav.dataset.route);const rb=e.target.closest('[data-route-btn]');if(rb)return navigate(rb.dataset.routeBtn);const course=e.target.closest('[data-course]');if(course)return navigate('course',{selectedCourse:course.dataset.course});const lesson=e.target.closest('[data-lesson]');if(lesson)return navigate('lesson',{selectedLesson:lesson.dataset.lesson});const fav=e.target.closest('[data-favorite]');if(fav)return toggleFavorite(fav.dataset.favorite);const comp=e.target.closest('[data-complete]');if(comp)return toggleComplete(comp.dataset.complete);const back=e.target.closest('[data-back]');if(back)return navigate(back.dataset.back);const font=e.target.closest('[data-font]');if(font)return setFontSize(font.dataset.font);const lang=e.target.closest('[data-lang]');if(lang){state.language=lang.dataset.lang;save();return render()}const setting=e.target.closest('[data-setting="theme"]');if(setting){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save();return render()}const cont=e.target.closest('[data-action="continue"]');if(cont){const first=lessons.find(l=>!state.completed.includes(l.id))||lessons[0];return navigate('lesson',{selectedLesson:first.id})}if(e.target.closest('[data-prev]')){const l=lessons.find(x=>x.id===state.selectedLesson),ls=lessons.filter(x=>x.courseId===l.courseId),i=ls.findIndex(x=>x.id===l.id);if(i>0)return navigate('lesson',{selectedLesson:ls[i-1].id})}if(e.target.closest('[data-next]')){const l=lessons.find(x=>x.id===state.selectedLesson),ls=lessons.filter(x=>x.courseId===l.courseId),i=ls.findIndex(x=>x.id===l.id);if(i<ls.length-1)return navigate('lesson',{selectedLesson:ls[i+1].id})}});
document.addEventListener('input',e=>{if(e.target.id==='lesson-search'||e.target.id==='course-search'){state.search=e.target.value;if(e.target.id==='lesson-search')renderSearch()}});
themeToggle?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save();render()});
applyFontScale();render();