const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();}
const API='https://clipsmalsum.duckdns.org/academy-api';
const state={route:'home',selectedCourse:'course-1',selectedLesson:'lesson-1',theme:localStorage.getItem('academy-theme')||'dark',language:localStorage.getItem('academy-language')||'ce',fontScale:Number(localStorage.getItem('academy-font-scale')||'.9'),favorites:JSON.parse(localStorage.getItem('academy-favorites')||'[]'),completed:JSON.parse(localStorage.getItem('academy-completed')||'[]'),search:''};
const I={
ru:{home:'Главная',courses:'Курсы',favorites:'Избранное',profile:'Профиль',quick:'Быстрый доступ',allSections:'Все учебные разделы',search:'Поиск',findLesson:'Найти нужный урок',savedLessons:'Сохранённые уроки',progress:'Прогресс',track:'Отслеживание прохождения',myProgress:'Мой прогресс',more:'Подробнее',lessonsDone:'Пройдено уроков',finished:'завершено',studySpace:'Учебное пространство',continueStudy:'Продолжить обучение',searchCourses:'Поиск по курсам и урокам',course:'Курс',allCourses:'Все курсы',studySection:'Учебный раздел',lessons:'Уроки',lesson:'Урок',audio:'Аудио',lessonAudio:'Аудио урока',initialText:'Начальный текст',materials:'Материалы',lessonPdf:'PDF к уроку',fileLater:'Файл будет добавлен позже',open:'Открыть',noPdf:'Для этого тестового урока PDF не предусмотрен.',inFavorites:'В избранном',toFavorites:'В избранное',lessonDone:'Урок пройден',markDone:'Отметить пройденным',previous:'Предыдущий',next:'Следующий',enterLesson:'Введите название урока',nothingFound:'Ничего не найдено',tryAnother:'Попробуйте другой запрос',empty:'Пока пусто',emptyFavorites:'Добавляйте уроки в избранное, чтобы быстро возвращаться к ним.',totalProgress:'Общий прогресс',passed:'Пройдено',testLessons:'тестовых уроков',passedLessons:'Пройденные уроки',noPassed:'Нет пройденных уроков',markHint:'Отметьте урок как пройденный, и он появится здесь.',academyStudent:'Ученик Академии',darkTheme:'Тёмная тема',lightTheme:'Светлая тема',enableLight:'Включить светлую тему',enableDark:'Включить тёмную тему',changeDesign:'Изменить оформление приложения',interfaceLanguage:'Язык интерфейса',now:'Сейчас',russian:'Русский',chechen:'Чеченский',about:'О версии',withoutMaterials:'Без настоящих материалов курса',addedFavorite:'Добавлено в избранное',removedFavorite:'Удалено из избранного',markedDone:'Урок отмечен как пройденный',markRemoved:'Отметка снята',playerLater:'Тестовый плеер: реальное аудио добавим позже',pdfLater:'PDF будет подключён позже'},
ce:{home:'Коьрта агIо',courses:'Курсаш',favorites:'Хаьржинарш',profile:'Профиль',quick:'Сиха аьтто',allSections:'Дешаран дерриге дакъош',search:'Лехар',findLesson:'Оьшуш йолу урок каро',savedLessons:'Iалашдина урокаш',progress:'Кхиам',track:'Чекхдаларна тIехьажар',myProgress:'Сан кхиам',more:'Кхин а дуьззина',lessonsDone:'Чекхдаьхна урокаш',finished:'чекхдаьккхина',studySpace:'Дешаран майда',continueStudy:'Дешар дIадахьа',searchCourses:'Курсашкахула а, урокашкахула а лехар',course:'Курс',allCourses:'Дерриге курсаш',studySection:'Дешаран дакъа',lessons:'Урокаш',lesson:'Урок',audio:'Аудио',lessonAudio:'Урокан аудио',initialText:'Юьхьанцара текст',materials:'ГIирсаш',lessonPdf:'Урокан PDF',fileLater:'Файл тIаьхьо тIетухур ю',open:'Схьаделлан',noPdf:'ХӀокху тестови урокан PDF ца карайо',inFavorites:'Хаьржинчехь',toFavorites:'Хаьржинчу',lessonDone:'Урок чекхдаьккхина',markDone:'Чекхдаьккхина аьлла билгалдан',previous:'Хьалхара',next:'ТIаьхьара',enterLesson:'Урокан цIе дIаязъе',nothingFound:'ХIума ца карийна',tryAnother:'Кхин дош леха хьажа',empty:'ХIинцака ясса ю',emptyFavorites:'Сиха юхаверзархьама, урокаш хьалхатеттинчу тIетиха',totalProgress:'Юкъара кхиам',passed:'Чекхдаьккхина',testLessons:'тестови урокаш',passedLessons:'Чекхдаьхна урокаш',noPassed:'Чекхдаьхна урокаш яц',markHint:'Урок чекхдаьккхина аьлла билгалбе, иза кхузахь гучуберг ю',academyStudent:'Академин дешархо',darkTheme:'Бодане тема',lightTheme:'Серламе тема',enableLight:'Серламе тема лато',enableDark:'Бодане тема лато',changeDesign:'Приложенин куц хийца',interfaceLanguage:'Интерфейсан мотт',now:'ХIинца',russian:'Оьрсийн',chechen:'Нохчийн',about:'Версех лаьцна',withoutMaterials:'Курсан баккъалла болу гIирсаш боцуш',addedFavorite:'Хьалхатеттинчу тIетоьхна',removedFavorite:'Хьалхатеттинчуьра дIаяьккхина',markedDone:'Урок чекхдаьккхина аьлла билгалйина',markRemoved:'Билгало дIаяьккхина',playerLater:'Тестови плеер: баккъалла долу аудио тIаьхьо тIетухур ду',pdfLater:'PDF тIаьхьо тIехоттур ю'}};
const t=k=>I[state.language][k]||k;
const courseAge='15 - ГlА БlЕ ШО';
const ageLabel=()=>`<div style="display:block;width:max-content;max-width:100%;margin:14px auto 6px;padding:8px 16px;border-radius:999px;text-align:center;font-size:calc(20px * var(--font-scale));line-height:1.15;font-weight:900;letter-spacing:.035em;background:${state.theme==='dark'?'#17382f':'#f4e4b8'};color:${state.theme==='dark'?'#fff4d6':'#0d3f33'};border:1px solid ${state.theme==='dark'?'rgba(244,228,184,.35)':'rgba(13,63,51,.18)'}">${courseAge}</div>`;
const lessonTitles=['1-ра дарс','2-гӀа дарс','3-гӀа дарс','4-гӀа дарс','5-гӀа дарс','6-гӀа дарс','7-гӀа дарс','8-гӀа дарс','9-гӀа дарс','10-гӀа дарс','11-гӀа дарс','12-гӀа дарс','13-гӀа дарс','14-гӀа дарс','15-гӀа дарс','16-гIа дарс','17-гIа дарс','18-гIа дарс','19-гIа дарс','20-гIа дарс'];
const lessons=lessonTitles.map((lessonTitle,i)=>({id:`lesson-${i+1}`,courseId:'course-1',number:i+1,title:lessonTitle,audio:`${API}/lesson/${i+1}/audio`}));
const courses=[{id:'course-1',title:'Курс 1',lessons:lessons.map(x=>x.id),pdf:`${API}/course/1/pdf`}];
const view=document.getElementById('view'),title=document.getElementById('page-title'),themeToggle=document.getElementById('theme-toggle');document.documentElement.dataset.theme=state.theme;
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]))}
function applyFontScale(){state.fontScale=Math.min(2,Math.max(.7,state.fontScale||.9));document.documentElement.style.setProperty('--font-scale',String(state.fontScale));}
function save(){localStorage.setItem('academy-theme',state.theme);localStorage.setItem('academy-language',state.language);localStorage.setItem('academy-font-scale',String(state.fontScale));localStorage.setItem('academy-favorites',JSON.stringify(state.favorites));localStorage.setItem('academy-completed',JSON.stringify(state.completed));}
function updateThemeButton(){if(!themeToggle)return;const dark=state.theme==='dark';themeToggle.innerHTML=`<span class="theme-symbol">${dark?'☀️':'🌙'}</span>`;themeToggle.setAttribute('aria-label',dark?t('enableLight'):t('enableDark'));themeToggle.title=dark?t('lightTheme'):t('darkTheme');}
function updateNav(){const labels={home:t('home'),courses:t('courses'),favorites:t('favorites'),profile:t('profile')};document.querySelectorAll('.nav-item').forEach(b=>{const s=b.querySelector('small');if(s)s.textContent=labels[b.dataset.route]||''});document.documentElement.lang=state.language==='ce'?'ce':'ru'}
function toast(m){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=m;requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>e.classList.remove('show'),1600)}
function haptic(){try{tg?.HapticFeedback?.impactOccurred('light')}catch(_){}}
function navigate(route,o={}){state.route=route;Object.assign(state,o);render();window.scrollTo({top:0,behavior:'smooth'});haptic()}
function setActiveNav(route){const base=['course','lesson','search','progress'].includes(route)?'courses':route;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===base||(route==='home'&&b.dataset.route==='home')))}
function progressValue(){return lessons.length?Math.round(state.completed.filter(id=>lessons.some(l=>l.id===id)).length/lessons.length*100):0}
function findLessons(query){const q=String(query||'').trim().toLowerCase();if(!q)return lessons;return lessons.filter(l=>String(l.number).includes(q)||l.title.toLowerCase().includes(q));}
function noSearchResults(){return `<div class="empty-state"><div class="empty-icon">⌕</div><h3>${t('nothingFound')}</h3><p>${t('tryAnother')}</p></div>`}
function renderHome(){title.textContent=t('home');const p=progressValue(),done=state.completed.filter(id=>lessons.some(l=>l.id===id)).length;view.innerHTML=`<section class="hero"><div class="hero-kicker">${t('studySpace')}</div><h2>Ӏакъидатан Академия</h2><p>${t('course')} 1 · 20 ${t('lessons')}</p><button class="primary-btn" data-action="continue">${t('continueStudy')}</button></section><div class="section-head"><h2>${t('quick')}</h2></div><section class="grid-2"><button class="card quick-card" data-route-btn="courses"><span class="quick-icon">▤</span><span><div class="quick-title">${t('courses')}</div><div class="quick-sub">${t('allSections')}</div></span></button><button class="card quick-card" data-route-btn="search"><span class="quick-icon">⌕</span><span><div class="quick-title">${t('search')}</div><div class="quick-sub">${t('findLesson')}</div></span></button><button class="card quick-card" data-route-btn="favorites"><span class="quick-icon">♡</span><span><div class="quick-title">${t('favorites')}</div><div class="quick-sub">${t('savedLessons')}</div></span></button><button class="card quick-card" data-route-btn="progress"><span class="quick-icon">◎</span><span><div class="quick-title">${t('progress')}</div><div class="quick-sub">${t('track')}</div></span></button></section><div class="section-head"><h2>${t('myProgress')}</h2><button class="link-btn" data-route-btn="progress">${t('more')}</button></div><section class="card progress-card"><div class="progress-row"><span>${t('lessonsDone')}</span><strong>${done}/${lessons.length}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><div class="quick-sub">${p}% ${t('finished')}</div></section>`}
function courseCards(){return courses.map((c,i)=>`<button class="course-card" data-course="${c.id}"><div class="course-top"><span class="badge">${t('course')} ${i+1}</span><span>›</span></div><h3>${c.title}</h3>${ageLabel()}<div class="quick-sub" style="margin-top:8px">${c.lessons.length} ${t('lessons')}</div></button>`).join('')}
function updateCourseSearchResults(){const box=document.getElementById('course-search-results');if(!box)return;const q=state.search.trim();if(!q){box.className='course-list';box.innerHTML=courseCards();return}const found=findLessons(q);box.className='lesson-list';box.innerHTML=found.length?found.map(lessonCard).join(''):noSearchResults()}
function renderCourses(){title.textContent=t('courses');view.innerHTML=`<div class="search-wrap"><input id="course-search" inputmode="search" autocomplete="off" placeholder="${t('searchCourses')}" value="${escapeHtml(state.search)}"><span>⌕</span></div><section id="course-search-results" class="course-list"></section>`;updateCourseSearchResults()}
function renderCourse(){const c=courses.find(x=>x.id===state.selectedCourse)||courses[0],ls=lessons.filter(l=>l.courseId===c.id);title.textContent=c.title;view.innerHTML=`<button class="link-btn" data-back="courses">← ${t('allCourses')}</button><section class="card"><span class="badge">${t('studySection')}</span><h2 style="margin:10px 0 6px">${c.title}</h2>${ageLabel()}<p style="margin:8px 0 0;color:var(--muted)">${ls.length} ${t('lessons')}</p></section><div class="section-head"><h2>${t('materials')}</h2></div><section class="card"><div class="progress-row"><strong style="display:flex;align-items:center;gap:10px"><svg aria-hidden="true" width="30" height="34" viewBox="0 0 24 28" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.5 1.5h10l5 5V26.5H4.5z" fill="#fff" stroke="#D94B45" stroke-width="1.5"/><path d="M14.5 1.5v5h5" fill="#F7D7D4" stroke="#D94B45" stroke-width="1.5"/><rect x="6.5" y="14" width="11" height="6.5" rx="1.5" fill="#D94B45"/><text x="12" y="18.6" text-anchor="middle" font-size="4.3" font-family="Arial,sans-serif" font-weight="700" fill="#fff">PDF</text></svg>${t('lessonPdf')}</strong><a class="secondary-btn" href="${c.pdf}" target="_blank" rel="noopener" style="text-decoration:none">${t('open')}</a></div></section><div class="section-head"><h2>${t('lessons')}</h2></div><section class="lesson-list">${ls.map(lessonCard).join('')}</section>`}
function lessonCard(l){const fav=state.favorites.includes(l.id),done=state.completed.includes(l.id);return `<article class="lesson-card ${done?'completed':''}"><div class="lesson-top"><button class="lesson-open" data-lesson="${l.id}"><span class="badge">${t('lesson')} ${l.number}</span><h3>${l.title}</h3><p>${t('audio')}</p></button><button class="favorite-btn" data-favorite="${l.id}" aria-label="${fav?t('inFavorites'):t('toFavorites')}">${fav?'♥':'♡'}</button></div></article>`}
function renderLesson(){const l=lessons.find(x=>x.id===state.selectedLesson)||lessons[0],idx=lessons.indexOf(l),fav=state.favorites.includes(l.id),done=state.completed.includes(l.id);title.textContent=l.title;view.innerHTML=`<div class="lesson-screen"><button class="link-btn" data-back="course">← ${courses[0].title}</button><section class="lesson-header"><span class="badge">${t('lesson')} ${l.number}</span><h2>${l.title}</h2>${ageLabel()}</section><section class="card"><div class="section-head"><h2>${t('lessonAudio')}</h2></div><audio controls preload="metadata" style="width:100%;margin-top:12px" src="${l.audio}"></audio></section><section class="row-actions"><button class="secondary-btn" data-favorite="${l.id}">${fav?'♥ '+t('inFavorites'):'♡ '+t('toFavorites')}</button><button class="secondary-btn" data-complete="${l.id}">${done?'✓ '+t('lessonDone'):t('markDone')}</button></section><section class="row-actions"><button class="secondary-btn" ${idx===0?'disabled':''} data-prev="${idx-1}">${t('previous')}</button><button class="secondary-btn" ${idx===lessons.length-1?'disabled':''} data-next="${idx+1}">${t('next')}</button></section></div>`}
function renderFavorites(){title.textContent=t('favorites');const favs=lessons.filter(l=>state.favorites.includes(l.id));if(!favs.length){view.innerHTML=`<section class="card empty-state"><div class="empty-icon">♡</div><h2>${t('empty')}</h2><p>${t('emptyFavorites')}</p></section>`;return}view.innerHTML=`<section class="lesson-list">${favs.map(lessonCard).join('')}</section>`}
function renderSearch(){title.textContent=t('search');view.innerHTML=`<div class="search-wrap"><input id="lesson-search" inputmode="search" autocomplete="off" placeholder="${t('enterLesson')}" value="${escapeHtml(state.search)}"><span>⌕</span></div><section id="lesson-search-results" class="lesson-list"></section>`;updateLessonSearchResults()}
function updateLessonSearchResults(){const box=document.getElementById('lesson-search-results');if(!box)return;const found=findLessons(state.search);box.innerHTML=found.length?found.map(lessonCard).join(''):noSearchResults()}
function renderProgress(){title.textContent=t('progress');const p=progressValue(),done=lessons.filter(l=>state.completed.includes(l.id));view.innerHTML=`<section class="card progress-card"><div class="progress-row"><span>${t('totalProgress')}</span><strong>${p}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><div class="quick-sub">${state.completed.length}/${lessons.length} ${t('passed')}</div></section><div class="section-head"><h2>${t('passedLessons')}</h2></div>${done.length?`<section class="lesson-list">${done.map(lessonCard).join('')}</section>`:`<section class="card empty-state"><h2>${t('noPassed')}</h2><p>${t('markHint')}</p></section>`}`}
function renderProfile(){title.textContent=t('profile');view.innerHTML=`<section class="card profile-row"><div class="avatar">ӀА</div><div><h3 style="margin:0">${t('academyStudent')}</h3><p style="margin:5px 0 0;color:var(--muted)">Telegram Mini App</p></div></section><div class="section-head"><h2>${t('changeDesign')}</h2></div><section class="card settings-list"><div class="setting-row"><div><strong>${state.theme==='dark'?t('darkTheme'):t('lightTheme')}</strong><div class="quick-sub">${state.theme==='dark'?t('enableLight'):t('enableDark')}</div></div><button class="icon-btn" data-theme-profile aria-label="${state.theme==='dark'?t('enableLight'):t('enableDark')}"><span class="theme-symbol">${state.theme==='dark'?'☀️':'🌙'}</span></button></div><div class="setting-row"><div><strong>Aa</strong></div><div class="font-controls"><button class="secondary-btn font-btn" data-font="minus">A−</button><button class="secondary-btn font-value" data-font="reset">${Math.round(state.fontScale*100)}%</button><button class="secondary-btn font-btn" data-font="plus">A+</button></div></div><div class="setting-row"><div><strong>${t('interfaceLanguage')}</strong><div class="quick-sub">${t('now')}: ${state.language==='ru'?t('russian'):t('chechen')}</div></div><div class="language-switch"><button class="secondary-btn ${state.language==='ru'?'selected':''}" data-language="ru">${t('russian')}</button><button class="secondary-btn ${state.language==='ce'?'selected':''}" data-language="ce">${t('chechen')}</button></div></div></section>`}
function render(){applyFontScale();updateThemeButton();updateNav();setActiveNav(state.route);({home:renderHome,courses:renderCourses,course:renderCourse,lesson:renderLesson,favorites:renderFavorites,search:renderSearch,progress:renderProgress,profile:renderProfile}[state.route]||renderHome)()}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route],[data-route-btn]');if(r){navigate(r.dataset.route||r.dataset.routeBtn);return}const c=e.target.closest('[data-course]');if(c){navigate('course',{selectedCourse:c.dataset.course});return}const l=e.target.closest('[data-lesson]');if(l){navigate('lesson',{selectedLesson:l.dataset.lesson});return}const f=e.target.closest('[data-favorite]');if(f){const id=f.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();return}const d=e.target.closest('[data-complete]');if(d){const id=d.dataset.complete;state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();render();return}const b=e.target.closest('[data-back]');if(b){navigate(b.dataset.back);return}const p=e.target.closest('[data-prev]');if(p){const i=Number(p.dataset.prev);if(i>=0)navigate('lesson',{selectedLesson:lessons[i].id});return}const n=e.target.closest('[data-next]');if(n){const i=Number(n.dataset.next);if(i<lessons.length)navigate('lesson',{selectedLesson:lessons[i].id});return}const a=e.target.closest('[data-action="continue"]');if(a){const next=lessons.find(x=>!state.completed.includes(x.id))||lessons[0];navigate('lesson',{selectedLesson:next.id});return}const th=e.target.closest('#theme-toggle,[data-theme-profile]');if(th){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;save();render();return}const lg=e.target.closest('[data-language]');if(lg){state.language=lg.dataset.language;save();render();return}const fs=e.target.closest('[data-font]');if(fs){if(fs.dataset.font==='minus')state.fontScale=Math.max(.7,Math.round((state.fontScale-.1)*10)/10);if(fs.dataset.font==='plus')state.fontScale=Math.min(2,Math.round((state.fontScale+.1)*10)/10);if(fs.dataset.font==='reset')state.fontScale=.9;save();render();return}});
document.addEventListener('input',e=>{if(e.target.id==='lesson-search'||e.target.id==='course-search'){state.search=e.target.value;if(e.target.id==='lesson-search')updateLessonSearchResults();else updateCourseSearchResults()}});
render();