(()=>{
const svg={home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7M5 9.5V21h14V9.5M9 21v-7h6v7"/></svg>',courses:'<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5zM4 5.5v16M8 7h8M8 11h8"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>',bot:'<svg viewBox="0 0 24 24"><rect x="4" y="7" width="16" height="13" rx="3"/><path d="M12 7V4M9 12h.01M15 12h.01M8 16h8"/><circle cx="12" cy="3.5" r="1"/></svg>',channel:'<svg viewBox="0 0 24 24"><path d="m21 4-3 17-6-5-1-6-5-2zM8 13l8-6"/></svg>',faq:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 4.5 1.8c-1.2 1.1-2 1.5-2 3M12 17h.01"/></svg>',share:'<svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.5-4.4M8.2 13.2l7.5 4.4"/></svg>',favorite:'<svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6z"/></svg>',theme:'<svg viewBox="0 0 24 24"><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="4"/></svg>',language:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></svg>',info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 10v6M12 7h.01"/></svg>'};
const CHANNEL_URL='https://t.me/Akidatan_Akademi_1',BOT_BASE='https://t.me/AkidatanAcademyAppBot',trigger=document.getElementById('side-menu-toggle');if(!trigger)return;
const ru={brand:'Ӏакъидатан Академия',brandSub:'Учебное пространство',sectionLearning:'Обучение',home:'Главная',courses:'Курсы',favorites:'Избранное',sectionAcademy:'АКАДЕМИЯ',channel:'Канал Академии',channelSub:'Новости, уроки и материалы',faq:'Вопросы и ответы',faqSub:'Частые вопросы об обучении',bot:'Помощь и вопросы',botSub:'Написать через Telegram-бота',share:'Поделиться приложением',sectionApp:'ПРИЛОЖЕНИЕ',profile:'Мой профиль',appearance:'Оформление',language:'Язык интерфейса',about:'Об Академии',footer:'Официальный канал и поддержка доступны через Telegram',aboutText1:'Учебное пространство для последовательного изучения уроков, сохранения избранного и отслеживания прогресса.',aboutText2:'Официальные новости и новые материалы публикуются в Telegram-канале Академии',faqTitle:'Вопросы и ответы',faq1q:'Как начать обучение?',faq1a:'Откройте «Курсы», выберите курс и начните с первого урока.',faq2q:'Как сохранить урок?',faq2a:'Откройте урок и добавьте его в «Избранное».',faq3q:'Как отметить урок пройденным?',faq3a:'Внутри урока используйте кнопку отметки о прохождении.',faq4q:'Как изменить язык и размер текста?',faq4a:'Откройте «Мой профиль» — там находятся настройки языка и оформления.',faq5q:'Где выходят новые материалы?',faq5a:'Новые материалы и объявления публикуются в официальном Telegram-канале Академии.',faqBot:'Не нашли ответ? Задать вопрос боту'};
const ce=ru;
function currentLanguage(){return (window.state?.language||localStorage.getItem('academy-language')||document.documentElement.lang||'ru')==='ce'?'ce':'ru'}
function labels(){return currentLanguage()==='ce'?ce:ru}
const backdrop=document.createElement('div');backdrop.className='side-menu-backdrop';document.body.appendChild(backdrop);
function item(a,i,l,s=''){return `<button class="side-menu-item" type="button" data-side-action="${a}"><span class="side-menu-icon">${i}</span><span class="side-menu-copy"><b>${l}</b>${s?`<small>${s}</small>`:''}</span><span class="side-menu-arrow">›</span></button>`}
function faq(q,a){return `<details class="side-menu-faq-item"><summary>${q}<span>+</span></summary><p>${a}</p></details>`}
function renderMenu(){const l=labels();backdrop.innerHTML=`<aside class="side-menu" role="dialog" aria-modal="true"><button class="side-menu-close" type="button" data-side-close>×</button><div class="side-menu-brand"><div class="side-menu-brand-mark">ӀА</div><div><strong>${l.brand}</strong><span>${l.brandSub}</span></div></div><div class="side-menu-section-title">${l.sectionLearning}</div><div class="side-menu-list">${item('home',svg.home,l.home)}</div><div class="side-menu-section-title">${l.sectionAcademy}</div><div class="side-menu-list">${item('channel',svg.channel,l.channel,l.channelSub)}${item('faq',svg.faq,l.faq,l.faqSub)}${item('bot',svg.bot,l.bot,l.botSub)}${item('share',svg.share,l.share)}</div><div class="side-menu-faq" data-side-faq aria-hidden="true"><button type="button" class="side-menu-faq-close" data-faq-close>×</button><div class="side-menu-faq-title">${l.faqTitle}</div><div class="side-menu-faq-list">${faq(l.faq1q,l.faq1a)}${faq(l.faq2q,l.faq2a)}${faq(l.faq3q,l.faq3a)}${faq(l.faq4q,l.faq4a)}${faq(l.faq5q,l.faq5a)}</div><button type="button" class="side-menu-faq-bot" data-side-action="bot">${l.faqBot}</button></div><div class="side-menu-section-title">${l.sectionApp}</div><div class="side-menu-list">${item('appearance',svg.theme,l.appearance)}${item('language',svg.language,l.language)}${item('about',svg.info,l.about)}</div><div class="side-menu-footer">${l.footer}</div></aside>`}
renderMenu();
function close(){backdrop.classList.remove('open');document.body.classList.remove('side-menu-open');trigger.setAttribute('aria-expanded','false')}
function go(r){close();navigate(r)}
function telegram(u){const t=window.Telegram?.WebApp;try{if(t?.openTelegramLink){t.openTelegramLink(u);return}}catch(_){}try{window.open(u,'_blank');return}catch(_){}try{window.location.href=u}catch(_){} }
function open(){renderMenu();backdrop.classList.add('open');document.body.classList.add('side-menu-open');trigger.setAttribute('aria-expanded','true')}
trigger.addEventListener('click',open);
backdrop.addEventListener('click',e=>{if(e.target===backdrop||e.target.closest('[data-side-close]')){e.preventDefault();e.stopPropagation();close();return}if(e.target.closest('[data-faq-close]')){e.preventDefault();e.stopPropagation();backdrop.querySelector('[data-side-faq]')?.classList.remove('open');return}const a=e.target.closest('[data-side-action]')?.dataset.sideAction;if(!a)return;e.preventDefault();e.stopPropagation();if(a==='home')return go('home');if(a==='courses')return go('courses');if(a==='profile')return go('profile');if(a==='favorites')return go('favorites');if(a==='appearance'||a==='language')return go('profile');if(a==='channel')return telegram(CHANNEL_URL);if(a==='bot'){const lang=currentLanguage();const url=`${BOT_BASE}?start=${lang==='ce'?'question_ce':'question_ru'}`;telegram(url);return}if(a==='share')return telegram(`https://t.me/share/url?url=${encodeURIComponent(BOT_BASE)}`);if(a==='faq'){const x=backdrop.querySelector('[data-side-faq]');x?.classList.add('open');x?.setAttribute('aria-hidden','false');return}if(a==='about'){const x=backdrop.querySelector('[data-side-about]');x?.classList.toggle('open');return}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&backdrop.classList.contains('open'))close()});
})();